# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6baf743f11540b2754227815ba5511d227ff1fcebc616c4e9734c62d9146040837bead1ff510d60318eed19c02ace887c85c27aa8ddafafd7132cf15b74b9a6

test:
  secret_key_base: 8edaee9f915810ea2b3646cf8ca676e9da30a15254bd3a634dd3e36599cf8e0d630fafc30e7c765aad9e849eb467461882eb06ded22bef171a5fa5902c21c95a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
